name: Tests

on:
  # if pushed directly to the master
  push:
    branches:
      - master
      - release/*
  # on a pull request
  pull_request:
    branches:
      - master
      - release/*

jobs:
  # runs unit tests with default config, submits the coverage report
  unit-test:
    name: Default Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check

      - name: Build Coverage Report
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: coverageReport

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml

  # Make sure it works with all standard JVMs on main OSes
  platform-test:
    name: Java ${{ matrix.java }}
    continue-on-error: ${{ matrix.java != '11' }}
    strategy:
      matrix:
        java: ["11", "12", "13", "14"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Check
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check